apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nats
  name: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nats
    spec:
      containers:
      - image: nats
        name: nats
        resources: 
          requests:
            memory: "300Mi"
            cpu: "0.1"
          limits:
            memory: "500Mi"
            cpu: "0.5"
status: {}
