apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
      - image: us-west1-docker.pkg.dev/store-microservices-430116/store-registry/payments-ms-prod
        name: payments-ms-prod
        env:
          - name: PORT
            value: "3000"
          - name: NATS_SERVERS
            value: "nats://nats-server:4222"
          - name: STRIPE_SUCCESS_URL
            value: "http://localhost:3004/payments/success"
          - name: STRIPE_CANCEL_URL
            value: "http://localhost:3004/payments/cancel"
          - name: STRIPE_SECRET
            valueFrom:
              secretKeyRef:
                name: payments-secrets
                key: stripe_secret
          - name: STRIPE_ENDPOINT_SECRET
            valueFrom:
              secretKeyRef:
                name: payments-secrets
                key: endpoint_secret
        resources: 
          requests:
            memory: "300Mi"
            cpu: "0.1"
          limits:
            memory: "500Mi"
            cpu: "0.5"
status: {}
