apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: client-gateway
  name: client-gateway-svc
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: client-gateway
  type: NodePort
status:
  loadBalancer: {}
